
# vagrant related settings
vagrant:
  # vagrant plugins are actually rubygems so you can declare to use any rubygems
  # common config level
  plugins:
    - _id: "essential-hostmanager"
      _id_deprecated: "essential-0"
      name: vagrant-hostmanager
      version: ""
      state: ""
      config_key: hostmanager
      enabled: false
      options:
        enabled: true
        manage_host: true
        manage_guest: true
